version: "2.1"
services:
  code-server:
    privileged: true
    build:
      context: ./
      dockerfile: Dockerfile
    # image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=password #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=password #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_BUCKET=code-server
      - S3_ENDPOINT=${S3_ENDPOINT}
      - GIT_USER_NAME=${GIT_USER_NAME}
      - GIT_USER_EMAIL=${GIT_USER_EMAIL}
      - CODE_FOLDER_DIR=/mnt/s3
      - TOKEN_NGROK=${TOKEN_NGROK}
      - DISPLAY=bdd-ui:0.0
      - HTTPS_PORTS=3000,8081
    depends_on:
      - bdd-ui
    devices:
      - "/dev/fuse"
    security_opt:
      # - apparmor:unconfined
      - "apparmor=unconfined"
    volumes:
      # - /path/to/appdata/config:/config
      - ./root/etc/s6-overlay/s6-rc.d/init-code-server/run:/etc/s6-overlay/s6-rc.d/init-code-server/run
      - ./root/usr/local/bin/install-extension:/usr/local/bin/install-extension
      - ./root/etc/s6-overlay/s6-rc.d/svc-code-server/run:/etc/s6-overlay/s6-rc.d/svc-code-server/run
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8443:8443
  
  bdd-ui:
    image: theasp/novnc:latest
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1200
      - RUN_XTERM=no
    ports:
      - "8080:8080"
