version: "2.1"
services:
  code-server:
    privileged: true
    build:
      context: ./
      dockerfile: Dockerfile
    # image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=password #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=password #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_BUCKET=code-server
      - S3_ENDPOINT=https://s3.filebase.com
    devices:
      - "/dev/fuse"
    security_opt:
      # - apparmor:unconfined
      - "apparmor=unconfined"
    volumes:
      # - /path/to/appdata/config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8443:8443